[package]
name = "mqtt"
version = "0.1.0"
authors = ["joham <jo.hamberger@live.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mqtt = "0.1.4"